"""Build an offline, frame-steppable gallery from the animation manifest."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
manifest = json.loads((ROOT/'assets/hodu/animations/manifest.json').read_text())
out = ROOT/'docs/design/previews/hodu-animations/index.html'
out.parent.mkdir(parents=True,exist_ok=True)
page = '''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>호두 · 애니메이션 원화</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f7f8fa;color:#20342a;font:15px/1.6 -apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo",sans-serif}main{max-width:1160px;margin:48px auto;padding:0 24px}h1{font-size:36px;letter-spacing:-.05em;margin:6px 0 12px}p{color:#66776c;margin:0 0 20px}.eyebrow{font-size:12px;letter-spacing:.12em;color:#547561}.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:28px 0}button,select{background:#fff;color:#315c49;border:1px solid #dce6df;border-radius:12px;font:inherit;padding:10px 16px;min-height:44px;cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #458966;outline-offset:3px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:20px}article{background:#fff;border:1px solid #e2e9e4;border-radius:22px;overflow:hidden}header{padding:20px 22px 4px}h2{font-size:19px;margin:0 0 4px}.id{font-size:11px;color:#819087}.stage{height:238px;display:grid;place-items:center;background:#f1f5f2;margin:14px;border-radius:16px}.dark .stage{background:#263d35}.sprite{width:208px;height:208px;background-repeat:no-repeat;image-rendering:pixelated;flex-shrink:0}.foot{padding:0 22px 22px}.scrub{display:flex;align-items:center;gap:10px}.scrub input{width:100%;accent-color:#315c49;min-height:32px}.frame-label{font-variant-numeric:tabular-nums;white-space:nowrap;font-size:12px}.links{display:flex;gap:14px;flex-wrap:wrap;margin-top:12px}a{font-size:12px;color:#315c49}footer{font-size:12px;color:#718076;margin:28px 0}.legend{display:inline-block;background:#eaf2ed;border-radius:99px;padding:5px 12px;font-size:12px}
@media(max-width:600px){main{margin:28px auto;padding:0 16px}h1{font-size:28px}.grid{grid-template-columns:1fr}}
</style><main><span class="eyebrow">WITHHODU · MOTION STUDIES</span><h1>호두가 움직이는 순간들.</h1><p>하나의 시트에 하나의 동작. 5가지 주제의 연속 도트 원화를 살펴보세요.<br>슬라이더를 움직이면 멈춘 상태에서 각 프레임을 자세히 볼 수 있어요.</p><span class="legend">실제 투명 PNG · 프레임별 시간 적용</span>
<div class="controls"><button id="play">일시정지</button><label>재생 속도 <select id="speed"><option value="0.5">0.5배</option><option value="1" selected>1배</option><option value="1.5">1.5배</option></select></label><button id="background">어두운 배경</button><button id="restart">처음부터</button></div><div class="grid" id="grid"></div><footer>원화 12프레임과 화면 주사율은 별개입니다. 가로 이동은 브라우저에서 부드럽게 합성하고, 발·앞발·표정은 이 원화로 교체합니다. 이 페이지는 자산 검토용이며 앱에 적용된 동작을 표시하는 화면은 아닙니다.</footer></main>
<script>
const manifest=__MANIFEST__,root='../../../../assets/hodu/animations/';let playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,speed=1,last=performance.now();
const items=manifest.animations.map(a=>{const article=document.createElement('article');article.innerHTML=`<header><h2>${a.title}</h2><span class="id">${a.id} · ${a.frameCount} frames</span></header><div class="stage"><div class="sprite" role="img" aria-label="${a.title}"></div></div><div class="foot"><div class="scrub"><input type="range" min="0" max="${a.frameCount-1}" value="0" step="1" aria-label="${a.title} 프레임"><span class="frame-label">01 / 12</span></div><div class="links"><a href="${root+a.sheet}">투명 시트</a><a href="${root+'previews/'+a.id+'-contact.png'}">전체 프레임</a><a href="${root+a.preview}">APNG</a></div></div>`;document.querySelector('#grid').append(article);const sprite=article.querySelector('.sprite'),slider=article.querySelector('input'),label=article.querySelector('.frame-label');sprite.style.backgroundImage=`url("${root+a.sheet}")`;sprite.style.backgroundSize=`${208*a.columns}px ${208*a.rows}px`;const item={a,sprite,slider,label,time:0};slider.oninput=()=>{playing=false;sync();item.time=a.durationsMs.slice(0,+slider.value).reduce((x,y)=>x+y,0);paint(item,+slider.value)};return item});
function paint(i,f){i.sprite.style.backgroundPosition=`${-(f%i.a.columns)*208}px ${-Math.floor(f/i.a.columns)*208}px`;i.slider.value=f;i.label.textContent=String(f+1).padStart(2,'0')+' / '+i.a.frameCount}
function sync(){document.querySelector('#play').textContent=playing?'일시정지':'재생'}sync();
document.querySelector('#play').onclick=()=>{playing=!playing;sync()};document.querySelector('#speed').onchange=e=>speed=+e.target.value;document.querySelector('#background').onclick=e=>{document.body.classList.toggle('dark');e.target.textContent=document.body.classList.contains('dark')?'밝은 배경':'어두운 배경'};document.querySelector('#restart').onclick=()=>items.forEach(i=>{i.time=0;paint(i,0)});
function tick(now){const delta=Math.min(now-last,100);last=now;if(playing)items.forEach(i=>{const total=i.a.durationsMs.reduce((x,y)=>x+y,0);i.time=(i.time+delta*speed)%total;let sum=0,f=0;for(;f<i.a.frameCount-1;f++){sum+=i.a.durationsMs[f];if(i.time<sum)break}paint(i,f)});requestAnimationFrame(tick)}items.forEach(i=>paint(i,0));requestAnimationFrame(tick);
</script></html>'''
out.write_text(page.replace('__MANIFEST__',json.dumps(manifest,ensure_ascii=False)))
print(out)
