[server]
runOnSave = true
fileWatcherType = "poll"
headless = false

[runner]
fastReruns = true

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#315C49"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#F1F4F3"
textColor = "#202B27"
font = "sans serif"
